import type { SubscriptionPlan } from '../types'

export type CanonicalPlanSlug = 'free' | 'starter' | 'growth' | 'business' | 'pro'

export const CANONICAL_PLAN_IDS: Record<CanonicalPlanSlug, string> = {
  free: 'plan-free',
  starter: 'plan-starter',
  growth: 'plan-growth',
  business: 'plan-business',
  pro: 'plan-pro',
}

export const CANONICAL_PLANS: Array<SubscriptionPlan & { slug: CanonicalPlanSlug }> = [
  {
    id: CANONICAL_PLAN_IDS.free,
    slug: 'free',
    name: 'FREE',
    description: 'للبداية بمتجر أساسي وحدود واضحة',
    priceMonthly: 0,
    priceYearly: 0,
    productLimit: 50,
    orderLimitPerMonth: 50,
    staffLimit: 1,
    storageLimit: 200,
    landingPagesLimit: 0,
    salesLinksLimit: 0,
    storeLimit: 1,
    trialDays: 0,
    launchPrice: 0,
    launchEnabled: false,
    features: ['واجهة متجر أساسية', 'إدارة المنتجات', 'الطلبات', 'العملاء', 'لوحة تحكم أساسية', 'تخصيص أساسي'],
    active: true,
    sortOrder: 0,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: false,
    variantInventory: false,
    coupons: false,
    abandonedCart: false,
    analytics: true,
    advancedReports: false,
    customDomain: false,
    apiAccess: false,
    removeBranding: false,
    prioritySupport: false,
  },
  {
    id: CANONICAL_PLAN_IDS.starter,
    slug: 'starter',
    name: 'STARTER',
    description: 'للمتاجر التي بدأت البيع وتحتاج أدوات تسويق أساسية',
    priceMonthly: 399,
    priceYearly: 3990,
    productLimit: 500,
    orderLimitPerMonth: 300,
    staffLimit: 3,
    storageLimit: 1024,
    landingPagesLimit: 1,
    salesLinksLimit: 10,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Free', 'نطاق مخصص', 'كوبونات', 'روابط بيع', 'تقارير أساسية', 'تخصيص المتجر', 'تنبيهات المخزون'],
    active: true,
    sortOrder: 1,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: false,
    variantInventory: true,
    coupons: true,
    abandonedCart: false,
    analytics: true,
    advancedReports: false,
    customDomain: true,
    apiAccess: false,
    removeBranding: false,
    prioritySupport: false,
  },
  {
    id: CANONICAL_PLAN_IDS.growth,
    slug: 'growth',
    name: 'GROWTH',
    description: 'للمتاجر النامية التي تحتاج تقارير وتحليلات أفضل',
    priceMonthly: 749,
    priceYearly: 7490,
    productLimit: 2000,
    orderLimitPerMonth: 1500,
    staffLimit: 10,
    storageLimit: 5120,
    landingPagesLimit: 5,
    salesLinksLimit: 50,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Starter', 'تقارير متقدمة', 'تحليلات متقدمة', 'رؤى مبيعات متقدمة', 'تخصيص أوسع', 'دعم أولوية عند توفره'],
    active: true,
    sortOrder: 2,
    isPopular: true,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: true,
    variantInventory: true,
    coupons: true,
    abandonedCart: true,
    analytics: true,
    advancedReports: true,
    customDomain: true,
    apiAccess: false,
    removeBranding: false,
    prioritySupport: true,
  },
  {
    id: CANONICAL_PLAN_IDS.business,
    slug: 'business',
    name: 'BUSINESS',
    description: 'للمتاجر التشغيلية التي تحتاج فريقاً أكبر وحدوداً أعلى',
    priceMonthly: 1099,
    priceYearly: 10990,
    productLimit: 5000,
    orderLimitPerMonth: 3500,
    staffLimit: 20,
    storageLimit: 10240,
    landingPagesLimit: 10,
    salesLinksLimit: 100,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Growth', 'صلاحيات فريق متقدمة', 'تحليلات محسنة', 'حدود تشغيل أكبر', 'دعم أولوية', 'أدوات تاجر متقدمة'],
    active: true,
    sortOrder: 3,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: true,
    variantInventory: true,
    coupons: true,
    abandonedCart: true,
    analytics: true,
    advancedReports: true,
    customDomain: true,
    apiAccess: false,
    removeBranding: false,
    prioritySupport: true,
  },
  {
    id: CANONICAL_PLAN_IDS.pro,
    slug: 'pro',
    name: 'PRO',
    description: 'للمتاجر الكبيرة التي تحتاج حدوداً أعلى وربطاً برمجياً',
    priceMonthly: 1499,
    priceYearly: 14990,
    productLimit: 0,
    orderLimitPerMonth: 10000,
    staffLimit: 50,
    storageLimit: 20480,
    landingPagesLimit: 20,
    salesLinksLimit: 0,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Business', 'وصول API عند توفره', 'أعلى حدود استخدام', 'تقارير متقدمة', 'قدرات فريق متقدمة', 'دعم مميز'],
    active: true,
    sortOrder: 4,
    isPopular: false,
    unlimitedProducts: true,
    unlimitedSalesLinks: true,
    quantityPricing: true,
    variantInventory: true,
    coupons: true,
    abandonedCart: true,
    analytics: true,
    advancedReports: true,
    customDomain: true,
    apiAccess: true,
    removeBranding: false,
    prioritySupport: true,
  },
]

export function canonicalPlanById(id?: string | null) {
  return CANONICAL_PLANS.find((plan) => plan.id === id || plan.slug === id) || null
}
