import type { SubscriptionPlan } from '../types'

export type CanonicalPlanSlug = 'free' | 'basic' | 'starter' | 'growth' | 'business' | 'pro' | 'lifetime'

export const CANONICAL_PLAN_IDS: Record<CanonicalPlanSlug, string> = {
  free: 'plan-free',
  basic: 'plan-basic',
  starter: 'plan-starter',
  growth: 'plan-growth',
  business: 'plan-business',
  pro: 'plan-pro',
  lifetime: 'plan-lifetime',
}

export const CANONICAL_PLANS: Array<SubscriptionPlan & { slug: CanonicalPlanSlug }> = [
  {
    id: CANONICAL_PLAN_IDS.free,
    slug: 'free',
    name: 'FREE',
    billingModel: 'subscription',
    oneTimePrice: 0,
    description: 'باقة تاريخية محفوظة للتوافق مع التجارب القائمة قبل إطلاق الباقات المدفوعة',
    priceMonthly: 0,
    priceYearly: 0,
    productLimit: 50,
    orderLimitPerMonth: 50,
    staffLimit: 1,
    storageLimit: 200,
    landingPagesLimit: 0,
    salesLinksLimit: 0,
    storeLimit: 1,
    trialDays: 30,
    launchPrice: 0,
    launchEnabled: false,
    features: ['متجر إلكتروني', 'إدارة المنتجات', 'الطلبات', 'العملاء', 'لوحة تحكم', 'تخصيص أساسي', 'تحليلات أساسية'],
    active: false,
    isPurchasable: false,
    archived: true,
    sortOrder: 0,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: false,
    variantInventory: false,
    coupons: false,
    analytics: true,
  },
  {
    id: CANONICAL_PLAN_IDS.basic,
    slug: 'basic',
    name: 'BASIC',
    billingModel: 'subscription',
    oneTimePrice: 0,
    description: 'الباقة الأساسية للمتاجر الجديدة',
    priceMonthly: 149,
    priceYearly: 1490,
    productLimit: 100,
    orderLimitPerMonth: 100,
    staffLimit: 2,
    storageLimit: 512,
    landingPagesLimit: 0,
    salesLinksLimit: 3,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['متجر إلكتروني', 'إدارة المنتجات', 'الطلبات', 'العملاء', 'لوحة تحكم'],
    active: true,
    sortOrder: 1,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: false,
    variantInventory: false,
    coupons: false,
    analytics: true,
  },
  {
    id: CANONICAL_PLAN_IDS.starter,
    slug: 'starter',
    name: 'STARTER',
    billingModel: 'subscription',
    oneTimePrice: 0,
    description: 'للمتاجر التي بدأت البيع وتحتاج أدوات تسويق أساسية',
    priceMonthly: 249,
    priceYearly: 2490,
    productLimit: 500,
    orderLimitPerMonth: 300,
    staffLimit: 3,
    storageLimit: 1024,
    landingPagesLimit: 1,
    salesLinksLimit: 10,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Basic', 'كوبونات', 'روابط بيع', 'صفحة هبوط واحدة', 'تخصيص المتجر', 'تنبيهات المخزون'],
    active: true,
    sortOrder: 2,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: false,
    variantInventory: true,
    coupons: true,
    analytics: true,
  },
  {
    id: CANONICAL_PLAN_IDS.growth,
    slug: 'growth',
    name: 'GROWTH',
    billingModel: 'subscription',
    oneTimePrice: 0,
    description: 'للمتاجر النامية التي تحتاج أدوات تشغيل أوسع',
    priceMonthly: 399,
    priceYearly: 3990,
    productLimit: 2000,
    orderLimitPerMonth: 1500,
    staffLimit: 10,
    storageLimit: 5120,
    landingPagesLimit: 5,
    salesLinksLimit: 50,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Starter', 'تسعير بالكمية', 'حدود تشغيل أعلى', 'صفحات هبوط متعددة', 'روابط بيع موسعة'],
    active: true,
    sortOrder: 3,
    isPopular: true,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: true,
    variantInventory: true,
    coupons: true,
    analytics: true,
  },
  {
    id: CANONICAL_PLAN_IDS.business,
    slug: 'business',
    name: 'BUSINESS',
    billingModel: 'subscription',
    oneTimePrice: 0,
    description: 'باقة تاريخية محفوظة للتوافق مع الاشتراكات القائمة',
    priceMonthly: 1099,
    priceYearly: 10990,
    productLimit: 5000,
    orderLimitPerMonth: 3500,
    staffLimit: 20,
    storageLimit: 10240,
    landingPagesLimit: 10,
    salesLinksLimit: 100,
    storeLimit: 1,
    trialDays: 0,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Growth', 'فريق أكبر', 'حدود تشغيل أكبر', 'تخزين موسع', 'أدوات تشغيل متقدمة'],
    active: false,
    isPurchasable: false,
    archived: true,
    sortOrder: 90,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: true,
    variantInventory: true,
    coupons: true,
    analytics: true,
  },
  {
    id: CANONICAL_PLAN_IDS.pro,
    slug: 'pro',
    name: 'PRO',
    billingModel: 'subscription',
    oneTimePrice: 0,
    description: 'للمتاجر الكبيرة التي تحتاج حدود استخدام وتشغيل أعلى',
    priceMonthly: 649,
    priceYearly: 6490,
    productLimit: 0,
    orderLimitPerMonth: 10000,
    staffLimit: 50,
    storageLimit: 20480,
    landingPagesLimit: 20,
    salesLinksLimit: 0,
    storeLimit: 1,
    trialDays: 3,
    launchPrice: 0,
    launchEnabled: false,
    features: ['كل مزايا Growth', 'أعلى حدود استخدام', 'منتجات غير محدودة', 'روابط بيع غير محدودة'],
    active: true,
    sortOrder: 4,
    isPopular: false,
    unlimitedProducts: true,
    unlimitedSalesLinks: true,
    quantityPricing: true,
    variantInventory: true,
    coupons: true,
    analytics: true,
  },
  {
    id: CANONICAL_PLAN_IDS.lifetime,
    slug: 'lifetime',
    name: 'LIFETIME',
    description: 'ملكية أساسية للمتجر بدفعة واحدة، بحدود واضحة',
    billingModel: 'one_time',
    oneTimePrice: 4999,
    isLaunchOffer: true,
    isPubliclyAvailable: true,
    launchOfferLimit: 0,
    launchOfferSoldCount: 0,
    launchOfferEndsAt: null,
    priceMonthly: 0,
    priceYearly: 0,
    productLimit: 1000,
    orderLimitPerMonth: 5000,
    staffLimit: 5,
    storageLimit: 5120,
    landingPagesLimit: 3,
    salesLinksLimit: 50,
    storeLimit: 1,
    trialDays: 0,
    launchPrice: 0,
    launchEnabled: false,
    features: ['ملكية أساسية غير منتهية', 'واجهة متجر', 'إدارة المنتجات والطلبات', 'كوبونات', 'تحليلات أساسية'],
    active: true,
    sortOrder: 5,
    isPopular: false,
    unlimitedProducts: false,
    unlimitedSalesLinks: false,
    quantityPricing: false,
    variantInventory: true,
    coupons: true,
    analytics: true,
  },
]

export function canonicalPlanById(id?: string | null) {
  return CANONICAL_PLANS.find((plan) => plan.id === id || plan.slug === id) || null
}
