import { FunctionalComponent } from 'preact'
import { useEffect, useState } from 'preact/hooks'
import { PageHeader } from '../../shared/components/ui/PageHeader'
import { Card } from '../../shared/components/ui/Card'
import { Loading } from '../../shared/components/ui/Loading'
import { finalizeShippingPartnerRevenuePeriodCallable, getShippingProviderCommercialAgreementCallable, getShippingPartnerRevenuePeriodCallable, markShippingPartnerRevenueSettledCallable } from '../../shared/services/auth'
import { listDocs } from '../../shared/utils/firestore'

const ShippingRevenue: FunctionalComponent = () => {
  const [loading, setLoading] = useState(true)
  const [rows, setRows] = useState<any[]>([]); const [month, setMonth] = useState(new Date().toISOString().slice(0, 7)); const [providerFilter, setProviderFilter] = useState('')
  const load = async () => { setLoading(true); try { const providers = await listDocs<any>('shippingProviders', { where: { status: { value: 'active' } } }); const next = []; for (const p of providers) { if (providerFilter && p.id !== providerFilter) continue; const agreement: any = await getShippingProviderCommercialAgreementCallable({ providerId: p.id }); const revenue: any = await getShippingPartnerRevenuePeriodCallable({ providerId: p.id, period: month }); next.push({ provider: p, agreement: agreement.data?.agreement, period: revenue.data?.period }) } setRows(next) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [month, providerFilter])
  return <div className="platform-operations"><PageHeader title="إيرادات الشحن" subtitle="إيرادات شركات الشحن منفصلة عن إيرادات الاشتراكات." /><div className="grid grid-2 mt-2"><label className="field"><span className="field-label">الشركة</span><select className="input" value={providerFilter} onChange={(e) => setProviderFilter((e.target as HTMLSelectElement).value)}><option value="">كل الشركات</option>{rows.map((row) => <option value={row.provider.id} key={row.provider.id}>{row.provider.name}</option>)}</select></label><label className="field"><span className="field-label">الشهر</span><input className="input" type="month" value={month} onChange={(e) => setMonth((e.target as HTMLInputElement).value)} /></label></div>{loading ? <Loading /> : <div className="card-grid">{rows.map((row) => <Card key={row.provider.id} title={row.provider.name}><div className="shipping-revenue-summary"><strong>{row.period?.totalRevenue == null ? '—' : `${row.period.totalRevenue} ج.م`}</strong><span>{row.period?.estimated ? 'تقديري' : row.period?.status || 'OPEN'} · {row.period?.shipmentVolume || 0} شحنة</span><small>Delivered: {row.period?.deliveredCount || 0} · Returned: {row.period?.returnedCount || 0} · Pending: {row.period?.pendingCount || 0}</small><small>حالة الاتفاق: {row.agreement?.status || 'غير مفعّل'}</small>{row.period?.status === 'OPEN' && <button type="button" onClick={() => void finalizeShippingPartnerRevenuePeriodCallable({ providerId: row.provider.id, period: month }).then(load)}>تثبيت الفترة</button>}{row.period?.status === 'FINALIZED' && <button type="button" onClick={() => void markShippingPartnerRevenueSettledCallable({ providerId: row.provider.id, period: month }).then(load)}>تحديد كمسوّاة</button>}</div></Card>)}</div>}</div>
}
export default ShippingRevenue
