import {
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Ban,
  Bell,
  Boxes,
  ChartBar,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  ChartPie,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  CirclePlus,
  Clock,
  Copy,
  CreditCard,
  Database,
  Donut,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  Gem,
  Globe,
  Headset,
  Hourglass,
  ImagePlus,
  Images,
  Info,
  LayoutDashboard,
  ScrollText,
  Send,
  LayoutGrid,
  LineChart,
  Link,
  Link2,
  LogIn,
  MonitorUp,
  List,
  ListOrdered,
  ListTodo,
  Bold,
  Italic,
  Underline,
  LockKeyhole,
  LogOut,
  Mail,
  MailCheck,
  Megaphone,
  Menu,
  Moon,
  Package,
  Palette,
  Pencil,
  FilePenLine,
  Plus,
  Quote,
  ReceiptText,
  RefreshCw,
  Rocket,
  Save,
  Search,
  SearchX,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Signal,
  SignalLow,
  SlidersHorizontal,
  Smartphone,
  Star,
  Store,
  Sun,
  Table2,
  Tag,
  Ticket,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Unlink,
  User,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
  WifiOff,
  Zap,
  X,
  CalendarDays,
  MoreHorizontal,
  Redo2,
  Printer,
  Milestone,
  Phone,
  Ruler,
  MapPin,
  Pin,
  PinOff,
  Undo2,
  StickyNote,
  MousePointerClick,
  Layers,
  type LucideIcon,
} from 'lucide-react'

/**
 * Canonical M&K icon mapping: every icon name used anywhere in the app maps to a
 * real Lucide component. Icons are rendered as inline SVGs (stroke = currentColor),
 * so an unknown/typo'd name can never leak as raw text into the UI — it falls back
 * to a safe icon instead. `scripts/check-icons.mjs` keeps source usage in sync with
 * this table.
 */
export const ICONS = {
  account_balance: CreditCard,
  account_balance_wallet: Wallet,
  account_circle: User,
  add: Plus,
  add_circle: CirclePlus,
  add_link: Link2,
  add_photo_alternate: ImagePlus,
  add_shopping_cart: ShoppingCart,
  admin_panel_settings: ShieldCheck,
  analytics: ChartNoAxesCombined,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  arrow_forward_ios: ChevronRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  bar_chart: ChartBar,
  block: Ban,
  bolt: Zap,
  swap_vert: ArrowDownUp,
  campaign: Megaphone,
  cancel: X,
  card_membership: CreditCard,
  category: Boxes,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  confirmation_number: Ticket,
  content_copy: Copy,
  dark_mode: Moon,
  delete: Trash2,
  database: Database,
  devices: MonitorUp,
  done_all: CheckCheck,
  donut: Donut,
  donut_small: Donut,
  download: Download,
  edit: Pencil,
  edit_document: FilePenLine,
  edit_note: FilePenLine,
  error: CircleAlert,
  fact_check: CheckCheck,
  format_quote: Quote,
  grid_view: LayoutGrid,
  gem: Gem,
  group_add: UserPlus,
  groups: Users,
  group: Users,
  groups_2: UsersRound,
  hourglass: Hourglass,
  hourglass_top: Hourglass,
  image: ImagePlus,
  photo_library: Images,
  info: Info,
  inventory: Package,
  inventory_2: Package,
  package: Package,
  package_2: Package,
  keyboard_arrow_down: ChevronDown,
  light_mode: Sun,
  link: Link,
  link_off: Unlink,
  login: LogIn,
  local_shipping: Truck,
  lock: LockKeyhole,
  logout: LogOut,
  mark_email_read: MailCheck,
  mark_email_unread: Mail,
  menu: Menu,
  notifications: Bell,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: CreditCard,
  pending_actions: ListTodo,
  person: User,
  person_add: UserPlus,
  query_stats: ChartNoAxesCombined,
  receipt_long: ReceiptText,
  refresh: RefreshCw,
  redo: Redo2,
  rocket_launch: Rocket,
  save: Save,
  format_bold: Bold,
  format_italic: Italic,
  format_underlined: Underline,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  policy: ScrollText,
  schedule: Clock,
  search: Search,
  send: Send,
  search_off: SearchX,
  sell: Tag,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shopping_cart: ShoppingCart,
  shopping_cart_checkout: ShoppingCart,
  shopping_cart_check: ShoppingCart,
  shopping_bag: ShoppingBag,
  show_chart: LineChart,
  monitoring: MonitorUp,
  pie_chart: ChartPie,
  signal_cellular_alt: Signal,
  signal_cellular_alt_1_bar: SignalLow,
  dashboard: LayoutDashboard,
  data_usage: ChartNoAxesCombined,
  space_dashboard: LayoutDashboard,
  star: Star,
  stars: Star,
  smartphone: Smartphone,
  store: Store,
  storefront: Store,
  sync_alt: RefreshCw,
  straighten: Ruler,
  route: Milestone,
  print: Printer,
  calendar_today: CalendarDays,
  more_vert: MoreHorizontal,
  pin: Pin,
  pin_off: PinOff,
  call: Phone,
  location_on: MapPin,
  note: StickyNote,
  mail: Mail,
  loyalty: Tag,
  ads_click: MousePointerClick,
  layers: Layers,
  public: Globe,
  support_agent: Headset,
  sync: RefreshCw,
  table_chart: Table2,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  attach_money: Wallet,
  favorite: Star,
  favorite_border: Star,
  rate_review: Star,
  verified: BadgeCheck,
  save_as: Save,
  verified_user: ShieldCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  undo: Undo2,
  warning: TriangleAlert,
  web: Globe,
  workspace_premium: Gem,
  // Historical names that used to leak as raw text — map them to safe real icons.
  done: Check,
  checkout: ShoppingCart,
  expand_more: ChevronDown,
  local_offer: Tag,
  signal_cellular_connected_no_internet_1_bar: WifiOff,
  ular_connected_no_internet_1_bar: WifiOff,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export const FALLBACK_ICON: LucideIcon = Info

export function isValidIcon(name: string): boolean {
  return name in ICONS
}

export function getIcon(name: string): LucideIcon {
  return ICONS[name as IconName] ?? FALLBACK_ICON
}
