import {
  Archive,
  ArrowDown,
  ArrowDownUp,
  ArrowRight,
  ArrowUp,
  BadgeCheck,
  Ban,
  Bell,
  Boxes,
  ChartBar,
  ChartNoAxesCombined,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleCheck,
  Clock,
  Copy,
  CreditCard,
  Donut,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  Gem,
  Globe,
  Headset,
  Hourglass,
  ImagePlus,
  Info,
  LayoutDashboard,
  LayoutGrid,
  LineChart,
  Link,
  Link2,
  ListTodo,
  LockKeyhole,
  LogOut,
  Mail,
  MailCheck,
  Megaphone,
  Menu,
  Moon,
  Package,
  Palette,
  Pencil,
  Plus,
  Quote,
  ReceiptText,
  RefreshCw,
  Rocket,
  Save,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingCart,
  Signal,
  SignalLow,
  Star,
  Store,
  Sun,
  Table2,
  Tag,
  Ticket,
  Trash2,
  TrendingUp,
  TriangleAlert,
  Truck,
  Unlink,
  User,
  UserPlus,
  Users,
  UsersRound,
  Wallet,
  WifiOff,
  X,
  type LucideIcon,
} from 'lucide-react'

/**
 * Canonical M&K icon mapping: every icon name used anywhere in the app maps to a
 * real Lucide component. Icons are rendered as inline SVGs (stroke = currentColor),
 * so an unknown/typo'd name can never leak as raw text into the UI — it falls back
 * to a safe icon instead. `scripts/check-icons.mjs` keeps source usage in sync with
 * this table.
 */
export const ICONS = {
  account_balance_wallet: Wallet,
  account_circle: User,
  add: Plus,
  add_link: Link2,
  add_photo_alternate: ImagePlus,
  admin_panel_settings: ShieldCheck,
  analytics: ChartNoAxesCombined,
  archive: Archive,
  arrow_forward: ArrowRight,
  arrow_forward_ios: ChevronRight,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  bar_chart: ChartBar,
  block: Ban,
  swap_vert: ArrowDownUp,
  campaign: Megaphone,
  cancel: X,
  card_membership: CreditCard,
  category: Boxes,
  check: Check,
  check_circle: CircleCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  confirmation_number: Ticket,
  content_copy: Copy,
  dark_mode: Moon,
  delete: Trash2,
  done_all: CheckCheck,
  donut_small: Donut,
  download: Download,
  edit: Pencil,
  error: CircleAlert,
  fact_check: CheckCheck,
  format_quote: Quote,
  grid_view: LayoutGrid,
  gem: Gem,
  group_add: UserPlus,
  groups: Users,
  groups_2: UsersRound,
  hourglass: Hourglass,
  hourglass_top: Hourglass,
  image: ImagePlus,
  info: Info,
  inventory: Package,
  inventory_2: Package,
  keyboard_arrow_down: ChevronDown,
  light_mode: Sun,
  link: Link,
  link_off: Unlink,
  local_shipping: Truck,
  lock: LockKeyhole,
  logout: LogOut,
  mark_email_read: MailCheck,
  mark_email_unread: Mail,
  menu: Menu,
  notifications: Bell,
  open_in_new: ExternalLink,
  palette: Palette,
  payments: CreditCard,
  pending_actions: ListTodo,
  person: User,
  person_add: UserPlus,
  query_stats: ChartNoAxesCombined,
  receipt_long: ReceiptText,
  rocket_launch: Rocket,
  save: Save,
  schedule: Clock,
  search: Search,
  sell: Tag,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shopping_cart: ShoppingCart,
  shopping_cart_checkout: ShoppingCart,
  show_chart: LineChart,
  signal_cellular_alt: Signal,
  signal_cellular_alt_1_bar: SignalLow,
  space_dashboard: LayoutDashboard,
  star: Star,
  store: Store,
  storefront: Store,
  support_agent: Headset,
  sync: RefreshCw,
  table_chart: Table2,
  trending_up: TrendingUp,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  visibility_off: EyeOff,
  warning: TriangleAlert,
  web: Globe,
  workspace_premium: Gem,
  // Historical names that used to leak as raw text — map them to safe real icons.
  done: Check,
  checkout: ShoppingCart,
  expand_more: ChevronDown,
  local_offer: Tag,
  signal_cellular_connected_no_internet_1_bar: WifiOff,
  ular_connected_no_internet_1_bar: WifiOff,
} satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

export const FALLBACK_ICON: LucideIcon = Info

export function isValidIcon(name: string): boolean {
  return name in ICONS
}

export function getIcon(name: string): LucideIcon {
  return ICONS[name as IconName] ?? FALLBACK_ICON
}
